key: Copper
theme:
  isolated: true

dashboardTiles:
  - type: 'submenu'
    menu:
      - type: 'submenu'
        width: 4
        vertical: true
        menu:
          - type: 'github'
            githubProject: 'copper-leaf/trellis'
            color: success
      - type: 'submenu'
        width: 8
        vertical: true
        menu:
          - type: 'github'
            githubProject: 'copper-leaf/clog'
            color: primary
  - type: 'submenu'
    menu:
      - type: 'submenu'
        width: 4
        vertical: true
        menu:
          - type: 'github'
            githubProject: 'copper-leaf/kudzu'
            color: info
          - type: 'github'
            githubProject: 'copper-leaf/krow'
            color: primary
      - type: 'submenu'
        width: 8
        vertical: true
        menu:
          - type: 'github'
            githubProject: 'JavaEden/Orchid'
            color: danger
  - type: 'submenu'
    color: info
    menu:
      - type: 'submenu'
        width: 12
        vertical: true
        menu:
          - type: 'latestPosts'
            title: Latest Blog Post
            limit: 1
            postsAtRoot: true
  - type: 'submenu'
    menu:
      - type: 'submenu'
        width: 4
        vertical: true
        menu:
          - type: 'page'
            itemId: 'home'
            title: Donec lobortis
            subtitle: Ut tempor sed nisi et scelerisque. Nam.
            color: success
          - type: 'page'
            itemId: 'home'
            title: Etiam pellentesque
            subtitle: Aliquam vitae metus at ante sagittis tristique.
            color: info
      - type: 'submenu'
        width: 4
        vertical: true
        menu:
          - type: 'page'
            itemId: 'home'
            title: Suspendisse potenti
            subtitle: Aliquam a ex non erat ultricies egestas.
            color: primary
      - type: 'submenu'
        width: 4
        vertical: true
        menu:
          - type: 'page'
            itemId: 'home'
            title: Donec ai
            subtitle: Class aptent taciti sociosqu ad litora torquent.
            color: success
          - type: 'page'
            itemId: 'home'
            title: Ut erat
            subtitle: Donec malesuada dui et sem congue mollis.
            color: info
