taxonomies:
  - key: group
    title: 'Plugins and Themes'
    single: true
    setAsPageParent: true
    permalink: 'plugins-and-themes/:archiveIndex'
    plugins:
      orderByDirection: asc
      permalink: ':term/:archiveIndex'
      orderBy:
        - 'title'
    themes:
      orderByDirection: asc
      permalink: ':term/:archiveIndex'
      orderBy:
        - 'title'
    bundles:
      orderByDirection: asc
      permalink: ':term/:archiveIndex'
      orderBy:
        - 'title'
  - key: category
    title: 'Categories'
    single: true
    setAsPageParent: true
    permalink: 'categories/:archiveIndex'
    includeFrom:
      - 'posts'
    orderBy:
      - 'publishDate'
    news:
      permalink: ':term/:archiveIndex'

# Page configurations
termArchivePages:
  layout: noBoxNoTitle
