sections:
  'user-manual':
    title: 'User Manual'
  'learn':
    title: 'Tutorials'

wikiPages:
  layout: noBoxNoTitle_menu
'user-manual':
  menu:
    - type: 'separator'
      title: 'User Manual'
      order: 1000
    - type: 'wiki'
      section: 'user-manual'
      order: 1010
'learn':
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100
    - type: 'pageIds'
      order: 110
      structure: nested

indexPages:
  template: 'wikiIndexPage'