# The config in this file should always exactly match `config-prod.yml`. This way, we can test a full production build
# without building in prod environment, which does a lot of additional optimizations we do not necessarily need yet.

services:
  generators:
    disabled:
      - 'javadoc'
      - 'groovydoc'
      - 'swiftdoc'

external:
  externalIndices:
    - collectionId: 'clog'
      url: 'https://javaeden.github.io/Clog/meta/javadoc.index.json'
    - collectionId: 'javaeden-common'
      url: 'https://javaeden.github.io/Common/meta/javadoc.index.json'
    - collectionId: 'krow'
      url: 'https://copper-leaf.github.io/krow/meta/kotlindoc.index.json'
