# These values shouldn't be changed during normal development. Instead, change values in `config-debug.yml` which will
# not affect production builds

services:
  generators:
    disabled:
      - 'javadoc'
      - 'groovydoc'
      - 'swiftdoc'
    
external:
  externalIndices:
    - collectionId: 'clog'
      url: 'https://javaeden.github.io/Clog/meta/javadoc.index.json'
    - collectionId: 'javaeden-common'
      url: 'https://javaeden.github.io/Common/meta/javadoc.index.json'
    - collectionId: 'krow'
      url: 'https://copper-leaf.github.io/krow/meta/kotlindoc.index.json'
