name: Release

on:
  push:
    branches:
    - master



jobs:
  test:
    name: Publish Release
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Release with Gradle
      run: ./gradlew build -Prelease -Penv=prod --dry-run
